#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VectorCompatSample.Resource", IsApplication=true)]

namespace VectorCompatSample
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.0.93")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int arrow_to_drawer_path = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int arrow_to_drawer_rotation = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int drawer_to_arrow_path = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int drawer_to_arrow_rotation = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int pause_to_play_path = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int pause_to_play_rotation = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int play_to_pause_path = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int play_to_pause_rotation = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int play_to_stop_path = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int play_to_stop_rotation = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int stop_to_play_path = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int stop_to_play_rotation = 2130771979;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F020000
			public const int morphButtonStyle = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int vc_autoMirrored = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int vc_autoStartAnimation = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int vc_backgroundTint = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int vc_backgroundTintMode = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int vc_endDrawable = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int vc_fillAlpha = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int vc_fillColor = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int vc_foregroundTint = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int vc_foregroundTintMode = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int vc_pathData = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int vc_startDrawable = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int vc_strokeAlpha = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int vc_strokeColor = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int vc_strokeLineCap = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int vc_strokeLineJoin = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int vc_strokeMiterLimit = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int vc_strokeWidth = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int vc_tint = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int vc_tintMode = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int vc_translateX = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int vc_translateY = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int vc_trimPathEnd = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int vc_trimPathOffset = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int vc_trimPathStart = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int vc_valueType = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int vc_viewportHeight = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int vc_viewportWidth = 2130837531;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F030000
			public const int background_tint_color = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int foreground_tint_color = 2130903041;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F040000
			public const int activity_horizontal_margin = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int activity_vertical_margin = 2130968577;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F050000
			public const int ic_arrow_to_drawer = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ic_arrow_vector = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ic_drawer_to_arrow = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int ic_drawer_vector = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int ic_pause_to_play = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int ic_pause_vector = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int ic_play_to_pause = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int ic_play_to_stop = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int ic_play_vector = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int ic_stop_to_play = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int ic_stop_vector = 2131034122;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F060000
			public const int action_settings = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int add = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int base_view = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int bevel = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int butt = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int checkBtn = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int drawerBtn = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int floatType = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int intType = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int miter = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int multiply = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int pathType = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int playBtn = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int round = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int screen = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int square = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int src_atop = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int src_in = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int src_over = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int stopBtn = 2131099667;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F070000
			public const int anim_duration = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F080000
			public const int activity_main = 2131230720;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F090000
			public const int menu_main = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F0A0000
			public const int ic_launcher = 2131361792;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0B0000
			public const int action_settings = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int app_name = 2131427329;
			
			// aapt resource value: 0x7F0B0002
			public const int hello_world = 2131427330;
			
			// aapt resource value: 0x7F0B0003
			public const int path_arrow = 2131427331;
			
			// aapt resource value: 0x7F0B0004
			public const int path_drawer = 2131427332;
			
			// aapt resource value: 0x7F0B0005
			public const int path_pause = 2131427333;
			
			// aapt resource value: 0x7F0B0006
			public const int path_play = 2131427334;
			
			// aapt resource value: 0x7F0B0007
			public const int path_stop = 2131427335;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0C0000
			public const int AppTheme = 2131492864;
			
			// aapt resource value: 0x7F0C0001
			public const int Widget_MorphButton = 2131492865;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x0 }
			public static int[] AnimatedVectorDrawable = new int[] {
					0};
			
			// aapt resource value: { 0x0,0x0 }
			public static int[] AnimatedVectorDrawableTarget = new int[] {
					0,
					0};
			
			// aapt resource value: 0
			public const int AnimatedVectorDrawableTarget_android_animation = 0;
			
			// aapt resource value: 1
			public const int AnimatedVectorDrawableTarget_android_name = 1;
			
			// aapt resource value: 0
			public const int AnimatedVectorDrawable_android_drawable = 0;
			
			// aapt resource value: { 0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x7F020019 }
			public static int[] Animator = new int[] {
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					2130837529};
			
			// aapt resource value: 0
			public const int Animator_android_duration = 0;
			
			// aapt resource value: 1
			public const int Animator_android_interpolator = 1;
			
			// aapt resource value: 2
			public const int Animator_android_repeatCount = 2;
			
			// aapt resource value: 3
			public const int Animator_android_repeatMode = 3;
			
			// aapt resource value: 4
			public const int Animator_android_startOffset = 4;
			
			// aapt resource value: 5
			public const int Animator_android_valueFrom = 5;
			
			// aapt resource value: 6
			public const int Animator_android_valueTo = 6;
			
			// aapt resource value: 7
			public const int Animator_vc_valueType = 7;
			
			// aapt resource value: { 0x0,0x7F020002,0x7F020003,0x7F020004,0x7F020005,0x7F020008,0x7F020009,0x7F02000B }
			public static int[] MorphButton = new int[] {
					0,
					2130837506,
					2130837507,
					2130837508,
					2130837509,
					2130837512,
					2130837513,
					2130837515};
			
			// aapt resource value: 0
			public const int MorphButton_android_scaleType = 0;
			
			// aapt resource value: 1
			public const int MorphButton_vc_autoStartAnimation = 1;
			
			// aapt resource value: 2
			public const int MorphButton_vc_backgroundTint = 2;
			
			// aapt resource value: 3
			public const int MorphButton_vc_backgroundTintMode = 3;
			
			// aapt resource value: 4
			public const int MorphButton_vc_endDrawable = 4;
			
			// aapt resource value: 5
			public const int MorphButton_vc_foregroundTint = 5;
			
			// aapt resource value: 6
			public const int MorphButton_vc_foregroundTintMode = 6;
			
			// aapt resource value: 7
			public const int MorphButton_vc_startDrawable = 7;
			
			// aapt resource value: { 0x0,0x7F02000A }
			public static int[] PropertyAnimator = new int[] {
					0,
					2130837514};
			
			// aapt resource value: 0
			public const int PropertyAnimator_android_propertyName = 0;
			
			// aapt resource value: 1
			public const int PropertyAnimator_vc_pathData = 1;
			
			// aapt resource value: { 0x7F020000 }
			public static int[] Theme = new int[] {
					2130837504};
			
			// aapt resource value: 0
			public const int Theme_morphButtonStyle = 0;
			
			// aapt resource value: { 0x0,0x0,0x0,0x0,0x7F020001,0x7F020012,0x7F020013,0x7F02001A,0x7F02001B }
			public static int[] VectorDrawable = new int[] {
					0,
					0,
					0,
					0,
					2130837505,
					2130837522,
					2130837523,
					2130837530,
					2130837531};
			
			// aapt resource value: { 0x0,0x7F02000A }
			public static int[] VectorDrawableClipPath = new int[] {
					0,
					2130837514};
			
			// aapt resource value: 0
			public const int VectorDrawableClipPath_android_name = 0;
			
			// aapt resource value: 1
			public const int VectorDrawableClipPath_vc_pathData = 1;
			
			// aapt resource value: { 0x0,0x0,0x0,0x0,0x0,0x0,0x7F020014,0x7F020015 }
			public static int[] VectorDrawableGroup = new int[] {
					0,
					0,
					0,
					0,
					0,
					0,
					2130837524,
					2130837525};
			
			// aapt resource value: 0
			public const int VectorDrawableGroup_android_name = 0;
			
			// aapt resource value: 1
			public const int VectorDrawableGroup_android_pivotX = 1;
			
			// aapt resource value: 2
			public const int VectorDrawableGroup_android_pivotY = 2;
			
			// aapt resource value: 3
			public const int VectorDrawableGroup_android_rotation = 3;
			
			// aapt resource value: 4
			public const int VectorDrawableGroup_android_scaleX = 4;
			
			// aapt resource value: 5
			public const int VectorDrawableGroup_android_scaleY = 5;
			
			// aapt resource value: 6
			public const int VectorDrawableGroup_vc_translateX = 6;
			
			// aapt resource value: 7
			public const int VectorDrawableGroup_vc_translateY = 7;
			
			// aapt resource value: { 0x0,0x7F020006,0x7F020007,0x7F02000A,0x7F02000C,0x7F02000D,0x7F02000E,0x7F02000F,0x7F020010,0x7F020011,0x7F020016,0x7F020017,0x7F020018 }
			public static int[] VectorDrawablePath = new int[] {
					0,
					2130837510,
					2130837511,
					2130837514,
					2130837516,
					2130837517,
					2130837518,
					2130837519,
					2130837520,
					2130837521,
					2130837526,
					2130837527,
					2130837528};
			
			// aapt resource value: 0
			public const int VectorDrawablePath_android_name = 0;
			
			// aapt resource value: 1
			public const int VectorDrawablePath_vc_fillAlpha = 1;
			
			// aapt resource value: 2
			public const int VectorDrawablePath_vc_fillColor = 2;
			
			// aapt resource value: 3
			public const int VectorDrawablePath_vc_pathData = 3;
			
			// aapt resource value: 4
			public const int VectorDrawablePath_vc_strokeAlpha = 4;
			
			// aapt resource value: 5
			public const int VectorDrawablePath_vc_strokeColor = 5;
			
			// aapt resource value: 6
			public const int VectorDrawablePath_vc_strokeLineCap = 6;
			
			// aapt resource value: 7
			public const int VectorDrawablePath_vc_strokeLineJoin = 7;
			
			// aapt resource value: 8
			public const int VectorDrawablePath_vc_strokeMiterLimit = 8;
			
			// aapt resource value: 9
			public const int VectorDrawablePath_vc_strokeWidth = 9;
			
			// aapt resource value: 10
			public const int VectorDrawablePath_vc_trimPathEnd = 10;
			
			// aapt resource value: 11
			public const int VectorDrawablePath_vc_trimPathOffset = 11;
			
			// aapt resource value: 12
			public const int VectorDrawablePath_vc_trimPathStart = 12;
			
			// aapt resource value: 0
			public const int VectorDrawable_android_alpha = 0;
			
			// aapt resource value: 1
			public const int VectorDrawable_android_height = 1;
			
			// aapt resource value: 2
			public const int VectorDrawable_android_name = 2;
			
			// aapt resource value: 3
			public const int VectorDrawable_android_width = 3;
			
			// aapt resource value: 4
			public const int VectorDrawable_vc_autoMirrored = 4;
			
			// aapt resource value: 5
			public const int VectorDrawable_vc_tint = 5;
			
			// aapt resource value: 6
			public const int VectorDrawable_vc_tintMode = 6;
			
			// aapt resource value: 7
			public const int VectorDrawable_vc_viewportHeight = 7;
			
			// aapt resource value: 8
			public const int VectorDrawable_vc_viewportWidth = 8;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
