#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.34209
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Totem.Resource", IsApplication=true)]

namespace Totem
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int font = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int totemblue = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int totembrown = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int totemdarkblue = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Berg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int grass = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_add_white_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_arrow_back_white_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_arrow_forward_white_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_close_white_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_delete_white_24dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_more_vert_white_24dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_search_white_24dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Lamp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Lijn_bold = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Totem = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080005
			public const int addButton = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int all_eigenschappen_list = 2131230727;
			
			// aapt resource value: 0x7f08000d
			public const int all_totem_list = 2131230733;
			
			// aapt resource value: 0x7f080000
			public const int backButton = 2131230720;
			
			// aapt resource value: 0x7f08001d
			public const int berg = 2131230749;
			
			// aapt resource value: 0x7f080028
			public const int body = 2131230760;
			
			// aapt resource value: 0x7f080008
			public const int bottomBar = 2131230728;
			
			// aapt resource value: 0x7f080010
			public const int checkbox = 2131230736;
			
			// aapt resource value: 0x7f080022
			public const int checkboxWeergeven = 2131230754;
			
			// aapt resource value: 0x7f08001b
			public const int checklist = 2131230747;
			
			// aapt resource value: 0x7f080013
			public const int child = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int childhead = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int childindent = 2131230741;
			
			// aapt resource value: 0x7f080001
			public const int closeButton = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int deleteButton = 2131230726;
			
			// aapt resource value: 0x7f08002b
			public const int deleteItem = 2131230763;
			
			// aapt resource value: 0x7f080024
			public const int detail = 2131230756;
			
			// aapt resource value: 0x7f08000f
			public const int eigenschap = 2131230735;
			
			// aapt resource value: 0x7f080019
			public const int eigenschappen = 2131230745;
			
			// aapt resource value: 0x7f08001e
			public const int empty_profiel = 2131230750;
			
			// aapt resource value: 0x7f08000e
			public const int expand = 2131230734;
			
			// aapt resource value: 0x7f08002a
			public const int freq = 2131230762;
			
			// aapt resource value: 0x7f080030
			public const int full = 2131230768;
			
			// aapt resource value: 0x7f08002d
			public const int grass = 2131230765;
			
			// aapt resource value: 0x7f080016
			public const int head = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int intro = 2131230743;
			
			// aapt resource value: 0x7f080011
			public const int jaKnop = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int neeKnop = 2131230738;
			
			// aapt resource value: 0x7f080025
			public const int number = 2131230757;
			
			// aapt resource value: 0x7f08001a
			public const int profielen = 2131230746;
			
			// aapt resource value: 0x7f08001f
			public const int profielen_list = 2131230751;
			
			// aapt resource value: 0x7f080003
			public const int query = 2131230723;
			
			// aapt resource value: 0x7f08002e
			public const int reset = 2131230766;
			
			// aapt resource value: 0x7f080023
			public const int scroll = 2131230755;
			
			// aapt resource value: 0x7f080004
			public const int searchButton = 2131230724;
			
			// aapt resource value: 0x7f08002f
			public const int select = 2131230767;
			
			// aapt resource value: 0x7f080009
			public const int selected = 2131230729;
			
			// aapt resource value: 0x7f080027
			public const int synonyms = 2131230759;
			
			// aapt resource value: 0x7f080021
			public const int tip = 2131230753;
			
			// aapt resource value: 0x7f080020
			public const int titel = 2131230752;
			
			// aapt resource value: 0x7f080002
			public const int title = 2131230722;
			
			// aapt resource value: 0x7f080026
			public const int title_synonyms = 2131230758;
			
			// aapt resource value: 0x7f080029
			public const int totem = 2131230761;
			
			// aapt resource value: 0x7f08002c
			public const int totem_list = 2131230764;
			
			// aapt resource value: 0x7f08001c
			public const int totempaal = 2131230748;
			
			// aapt resource value: 0x7f080018
			public const int totems = 2131230744;
			
			// aapt resource value: 0x7f08000a
			public const int vind = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int vindButton = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int vindText = 2131230731;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActionBar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AllEigenschappen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AllTotems = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Checklist = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EigenschapListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Eigenschappen = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ExpandChild = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ExpandChildHead = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ExpandChildIndent = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ExpandHeadFoot = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ExpandParent = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Main = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Profielen = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SplashScreen = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int TipPopUp = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int TotemDetail = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int TotemListItem = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Totems = 2130903057;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int EigenschapSelectieMenu = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Popup = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int DIN_light = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int DIN_regular = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int Sketchblock = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int Verveine = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppThemeNoAction = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int MyActionBar = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int MyCustomTheme_OverFlow = 2131099651;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CustomFont = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int CustomFont_font = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
