#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.34209
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Totem.Resource", IsApplication=true)]

namespace Totem
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001c
			public const int Verwijder = 2131099676;
			
			// aapt resource value: 0x7f060001
			public const int all_eigenschappen_list = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int all_totem_list = 2131099651;
			
			// aapt resource value: 0x7f060014
			public const int body = 2131099668;
			
			// aapt resource value: 0x7f060005
			public const int checkbox = 2131099653;
			
			// aapt resource value: 0x7f06000f
			public const int checkboxWeergeven = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int detail = 2131099665;
			
			// aapt resource value: 0x7f060004
			public const int eigenschap = 2131099652;
			
			// aapt resource value: 0x7f06000b
			public const int empty_profiel = 2131099659;
			
			// aapt resource value: 0x7f060017
			public const int freq = 2131099671;
			
			// aapt resource value: 0x7f060006
			public const int jaKnop = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int neeKnop = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int profielen = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int profielen_list = 2131099660;
			
			// aapt resource value: 0x7f060000
			public const int query = 2131099648;
			
			// aapt resource value: 0x7f060019
			public const int reset = 2131099673;
			
			// aapt resource value: 0x7f060010
			public const int scroll = 2131099664;
			
			// aapt resource value: 0x7f06001a
			public const int select = 2131099674;
			
			// aapt resource value: 0x7f060013
			public const int synonyms = 2131099667;
			
			// aapt resource value: 0x7f06000e
			public const int tip = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int titel = 2131099661;
			
			// aapt resource value: 0x7f060012
			public const int title = 2131099666;
			
			// aapt resource value: 0x7f060016
			public const int totem = 2131099670;
			
			// aapt resource value: 0x7f060009
			public const int totemBepalen = 2131099657;
			
			// aapt resource value: 0x7f060018
			public const int totem_list = 2131099672;
			
			// aapt resource value: 0x7f060008
			public const int totems = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int vind_button = 2131099650;
			
			// aapt resource value: 0x7f06001b
			public const int voegProfielToe = 2131099675;
			
			// aapt resource value: 0x7f060015
			public const int voegtoe = 2131099669;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AllEigenschappen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AllTotems = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EigenschapListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Eigenschappen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Profielen = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SplashScreen = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int TipPopUp = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TotemDetail = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int TotemListItem = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Totems = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int EigenschapSelectieMenu = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Popup = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int profielMenu = 2131034114;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
