#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.42000
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Totem.Resource", IsApplication=true)]

namespace Totem
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int all_totem_list = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int body = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int detail = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int eigenschap = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int freq = 2131034125;
			
			// aapt resource value: 0x7f050003
			public const int jaKnop = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int neeKnop = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int query = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int scroll = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int synonyms = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int title = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int totem = 2131034124;
			
			// aapt resource value: 0x7f050006
			public const int totemBepalen = 2131034118;
			
			// aapt resource value: 0x7f05000e
			public const int totem_list = 2131034126;
			
			// aapt resource value: 0x7f050005
			public const int totems = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AllTotems = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Eigenschappen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TotemDetail = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TotemListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Totems = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
