// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TotemAppIos
{
	public partial class TitleTableViewCell : BaseChecklistTableViewCell
	{
		public TitleTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
