#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ServiceStackTextSampleAndroid.Resource", IsApplication=true)]

namespace ServiceStackTextSampleAndroid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.0.93")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int buttonCurrentConditions = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int buttonDescription = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int buttonForecast = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int buttonGuid = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int buttonLinkToSite = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int buttonParse = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int buttonShowJson = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int tableLayout1 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int tableRow1 = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int tableRow2 = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int tableRow3 = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int textView1 = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int textView10 = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int textView11 = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int textView12 = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int textView3 = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int textViewCode = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int textViewDate = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int textViewHigh = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int textViewLatitude = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int textViewLocation = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int textViewLongitude = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int textViewLow = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int textViewTemp = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int textViewText = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int webView = 2130837529;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int currentconditionsitemlayout = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int forecastitemlayout = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int htmlactivitylayout = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int weatheractivitylayout = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int hello = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
