#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TotemAndroid.Resource", IsApplication=true)]

namespace TotemAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040003
			public const int bezinning = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int geven = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int totemopdrachten = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int voorbereiding = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int font = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int totemblue = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int totembrown = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int totemdarkblue = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Berg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int grass_green = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_add_white_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_arrow_back_white_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_arrow_forward_white_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_close_white_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_delete_white_24dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_more_vert_white_24dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_search_white_24dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Lamp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Lijn_bold = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Totem = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090005
			public const int addButton = 2131296261;
			
			// aapt resource value: 0x7f090007
			public const int all_eigenschappen_list = 2131296263;
			
			// aapt resource value: 0x7f09000d
			public const int all_totem_list = 2131296269;
			
			// aapt resource value: 0x7f090000
			public const int backButton = 2131296256;
			
			// aapt resource value: 0x7f09001e
			public const int berg = 2131296286;
			
			// aapt resource value: 0x7f090029
			public const int body = 2131296297;
			
			// aapt resource value: 0x7f090008
			public const int bottomBar = 2131296264;
			
			// aapt resource value: 0x7f090010
			public const int checkbox = 2131296272;
			
			// aapt resource value: 0x7f090023
			public const int checkboxWeergeven = 2131296291;
			
			// aapt resource value: 0x7f09001b
			public const int checklist = 2131296283;
			
			// aapt resource value: 0x7f090013
			public const int child = 2131296275;
			
			// aapt resource value: 0x7f090014
			public const int childhead = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int childindent = 2131296277;
			
			// aapt resource value: 0x7f090001
			public const int closeButton = 2131296257;
			
			// aapt resource value: 0x7f090006
			public const int deleteButton = 2131296262;
			
			// aapt resource value: 0x7f09002c
			public const int deleteItem = 2131296300;
			
			// aapt resource value: 0x7f090025
			public const int detail = 2131296293;
			
			// aapt resource value: 0x7f09000f
			public const int eigenschap = 2131296271;
			
			// aapt resource value: 0x7f090019
			public const int eigenschappen = 2131296281;
			
			// aapt resource value: 0x7f09001f
			public const int empty_profiel = 2131296287;
			
			// aapt resource value: 0x7f09000e
			public const int expand = 2131296270;
			
			// aapt resource value: 0x7f09002b
			public const int freq = 2131296299;
			
			// aapt resource value: 0x7f090031
			public const int full = 2131296305;
			
			// aapt resource value: 0x7f09002e
			public const int grass_green = 2131296302;
			
			// aapt resource value: 0x7f090016
			public const int head = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int intro = 2131296279;
			
			// aapt resource value: 0x7f090011
			public const int jaKnop = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int neeKnop = 2131296274;
			
			// aapt resource value: 0x7f090026
			public const int number = 2131296294;
			
			// aapt resource value: 0x7f09001a
			public const int profielen = 2131296282;
			
			// aapt resource value: 0x7f090020
			public const int profielen_list = 2131296288;
			
			// aapt resource value: 0x7f090003
			public const int query = 2131296259;
			
			// aapt resource value: 0x7f09002f
			public const int reset = 2131296303;
			
			// aapt resource value: 0x7f090024
			public const int scroll = 2131296292;
			
			// aapt resource value: 0x7f090004
			public const int searchButton = 2131296260;
			
			// aapt resource value: 0x7f090030
			public const int select = 2131296304;
			
			// aapt resource value: 0x7f090009
			public const int selected = 2131296265;
			
			// aapt resource value: 0x7f090028
			public const int synonyms = 2131296296;
			
			// aapt resource value: 0x7f09001c
			public const int tinder = 2131296284;
			
			// aapt resource value: 0x7f090022
			public const int tip = 2131296290;
			
			// aapt resource value: 0x7f090021
			public const int titel = 2131296289;
			
			// aapt resource value: 0x7f090002
			public const int title = 2131296258;
			
			// aapt resource value: 0x7f090027
			public const int title_synonyms = 2131296295;
			
			// aapt resource value: 0x7f09002a
			public const int totem = 2131296298;
			
			// aapt resource value: 0x7f09002d
			public const int totem_list = 2131296301;
			
			// aapt resource value: 0x7f09001d
			public const int totempaal = 2131296285;
			
			// aapt resource value: 0x7f090018
			public const int totems = 2131296280;
			
			// aapt resource value: 0x7f09000a
			public const int vind = 2131296266;
			
			// aapt resource value: 0x7f09000c
			public const int vindButton = 2131296268;
			
			// aapt resource value: 0x7f09000b
			public const int vindText = 2131296267;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActionBar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AllEigenschappen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AllTotems = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Checklist = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EigenschapListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Eigenschappen = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ExpandChild = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ExpandChildHead = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ExpandChildIndent = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ExpandHeadFoot = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ExpandParent = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Main = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Profielen = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SplashScreen = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int TipPopUp = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int TotemDetail = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int TotemListItem = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Totems = 2130903057;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int EigenschapSelectieMenu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int Popup = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060002
			public const int DIN_light = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int DIN_regular = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int Sketchblock = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int Verveine = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int checklist_foot = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int checklist_head = 2131099653;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppBaseTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AppThemeNoAction = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int MyActionBar = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int MyCustomTheme_OverFlow = 2131165187;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CustomFont = new int[]
			{
					2130771968};
			
			// aapt resource value: 0
			public const int CustomFont_font = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
